import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import React from "react";
import classes from "./layout.module.scss";
import Header from "@/components/header/Header";
import {HeaderLinks} from "@/components/header/types";
import Footer from "@/components/footer/Footer";
import MainContainer from "@/components/containers/MainContainer";

const inter = Roboto({ subsets: ['latin', "cyrillic"], weight: ["400", "700"] })

export const metadata: Metadata = {
  title: '4u | Online bank',
  description: 'Generated by create next app',
}

const links: HeaderLinks = [
  {label: 'Пополнить', href: '/replenishment', id: 1},
  {label: 'Перевести', href: '/translation', id: 2},
  {label: 'Аккаунт', href: '/profile', id: 3},
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <div className={classes.App}>
          <div className={classes.gradient}></div>
          <Header links={links}/>
          <MainContainer>
            {children}
          </MainContainer>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
